name: Frontend

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  typecheck:
    name: typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install
        working-directory: ./frontend
      - run: bun run build
        working-directory: ./frontend
      - run: echo "testing workflow failure retries" && exit 1
